# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/teracube/mt6765-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter emerald zirconia,$(TARGET_DEVICE)),)

endif
