# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/teracube/zirconia/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/teracube/zirconia

PRODUCT_COPY_FILES += \
    vendor/teracube/zirconia/proprietary/system/lib/libteeservice_client.trustonic.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libteeservice_client.trustonic.so \
    vendor/teracube/zirconia/proprietary/system/lib64/libteeservice_client.trustonic.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libteeservice_client.trustonic.so \
    vendor/teracube/zirconia/proprietary/vendor/bin/hw/android.hardware.gatekeeper@1.0-service.itrusty:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.gatekeeper@1.0-service.itrusty \
    vendor/teracube/zirconia/proprietary/vendor/bin/hw/vendor.mediatek.hardware.keymaster_attestation@1.1-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.mediatek.hardware.keymaster_attestation@1.1-service \
    vendor/teracube/zirconia/proprietary/vendor/bin/init_thh:$(TARGET_COPY_OUT_VENDOR)/bin/init_thh \
    vendor/teracube/zirconia/proprietary/vendor/bin/istorageproxyd:$(TARGET_COPY_OUT_VENDOR)/bin/istorageproxyd \
    vendor/teracube/zirconia/proprietary/vendor/bin/teei_loader:$(TARGET_COPY_OUT_VENDOR)/bin/teei_loader \
    vendor/teracube/zirconia/proprietary/vendor/etc/init/android.hardware.gatekeeper@1.0-service.itrusty.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper@1.0-service.itrusty.rc \
    vendor/teracube/zirconia/proprietary/vendor/etc/init/init.fpsensor.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.fpsensor.rc \
    vendor/teracube/zirconia/proprietary/vendor/etc/init/microtrust.init_thh.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/microtrust.init_thh.rc \
    vendor/teracube/zirconia/proprietary/vendor/etc/init/microtrust.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/microtrust.rc \
    vendor/teracube/zirconia/proprietary/vendor/etc/init/microtrust.storage.file.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/microtrust.storage.file.rc \
    vendor/teracube/zirconia/proprietary/vendor/etc/init/microtrust.storage.proinfo.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/microtrust.storage.proinfo.rc \
    vendor/teracube/zirconia/proprietary/vendor/etc/init/microtrust.storage.rpmb.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/microtrust.storage.rpmb.rc \
    vendor/teracube/zirconia/proprietary/vendor/etc/init/vendor.mediatek.hardware.keymaster_attestation@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.keymaster_attestation@1.1-service.rc \
    vendor/teracube/zirconia/proprietary/vendor/lib/hw/keystore.itrusty.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/keystore.itrusty.so \
    vendor/teracube/zirconia/proprietary/vendor/lib/hw/keystore.mt6765.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/keystore.mt6765.so \
    vendor/teracube/zirconia/proprietary/vendor/lib/hw/kmsetkey.default.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/kmsetkey.default.so \
    vendor/teracube/zirconia/proprietary/vendor/lib/hw/kmsetkey.itrusty.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/kmsetkey.itrusty.so \
    vendor/teracube/zirconia/proprietary/vendor/lib/hw/libSoftGatekeeper.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/libSoftGatekeeper.so \
    vendor/teracube/zirconia/proprietary/vendor/lib/hw/vendor.mediatek.hardware.keymaster_attestation@1.1-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/vendor.mediatek.hardware.keymaster_attestation@1.1-impl.so \
    vendor/teracube/zirconia/proprietary/vendor/lib/libitrusty.so:$(TARGET_COPY_OUT_VENDOR)/lib/libitrusty.so \
    vendor/teracube/zirconia/proprietary/vendor/lib/libkeymaster3device.so:$(TARGET_COPY_OUT_VENDOR)/lib/libkeymaster3device.so \
    vendor/teracube/zirconia/proprietary/vendor/lib/libkeymaster_messages.so:$(TARGET_COPY_OUT_VENDOR)/lib/libkeymaster_messages.so \
    vendor/teracube/zirconia/proprietary/vendor/lib/libkeymaster_portable.so:$(TARGET_COPY_OUT_VENDOR)/lib/libkeymaster_portable.so \
    vendor/teracube/zirconia/proprietary/vendor/lib/libkeystore-wifi-hidl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libkeystore-wifi-hidl.so \
    vendor/teracube/zirconia/proprietary/vendor/lib/libpuresoftkeymasterdevice.so:$(TARGET_COPY_OUT_VENDOR)/lib/libpuresoftkeymasterdevice.so \
    vendor/teracube/zirconia/proprietary/vendor/lib/libsoft_attestation_cert.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsoft_attestation_cert.so \
    vendor/teracube/zirconia/proprietary/vendor/lib/libsoftkeymasterdevice.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsoftkeymasterdevice.so \
    vendor/teracube/zirconia/proprietary/vendor/lib/libthha.so:$(TARGET_COPY_OUT_VENDOR)/lib/libthha.so \
    vendor/teracube/zirconia/proprietary/vendor/lib/libtrusty.so:$(TARGET_COPY_OUT_VENDOR)/lib/libtrusty.so \
    vendor/teracube/zirconia/proprietary/vendor/lib/libwapi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libwapi.so \
    vendor/teracube/zirconia/proprietary/vendor/lib/vendor.mediatek.hardware.keymaster_attestation@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.mediatek.hardware.keymaster_attestation@1.0.so \
    vendor/teracube/zirconia/proprietary/vendor/lib/vendor.mediatek.hardware.keymaster_attestation@1.1.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.mediatek.hardware.keymaster_attestation@1.1.so \
    vendor/teracube/zirconia/proprietary/vendor/lib64/hw/android.hardware.gatekeeper@1.0-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/android.hardware.gatekeeper@1.0-impl.so \
    vendor/teracube/zirconia/proprietary/vendor/lib64/hw/fpsensor_fingerprint.default.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/fpsensor_fingerprint.default.so \
    vendor/teracube/zirconia/proprietary/vendor/lib64/hw/gatekeeper.default.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/gatekeeper.default.so \
    vendor/teracube/zirconia/proprietary/vendor/lib64/hw/keystore.itrusty.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/keystore.itrusty.so \
    vendor/teracube/zirconia/proprietary/vendor/lib64/hw/keystore.mt6765.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/keystore.mt6765.so \
    vendor/teracube/zirconia/proprietary/vendor/lib64/hw/kmsetkey.default.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/kmsetkey.default.so \
    vendor/teracube/zirconia/proprietary/vendor/lib64/hw/kmsetkey.itrusty.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/kmsetkey.itrusty.so \
    vendor/teracube/zirconia/proprietary/vendor/lib64/hw/libSoftGatekeeper.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/libSoftGatekeeper.so \
    vendor/teracube/zirconia/proprietary/vendor/lib64/hw/vendor.mediatek.hardware.keymaster_attestation@1.1-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/vendor.mediatek.hardware.keymaster_attestation@1.1-impl.so \
    vendor/teracube/zirconia/proprietary/vendor/lib64/libchiponeic_fingerprint_factory.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libchiponeic_fingerprint_factory.so \
    vendor/teracube/zirconia/proprietary/vendor/lib64/libfp_ext_svc2.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libfp_ext_svc2.so \
    vendor/teracube/zirconia/proprietary/vendor/lib64/libitrusty.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libitrusty.so \
    vendor/teracube/zirconia/proprietary/vendor/lib64/libkeymaster3device.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libkeymaster3device.so \
    vendor/teracube/zirconia/proprietary/vendor/lib64/libkeymaster_messages.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libkeymaster_messages.so \
    vendor/teracube/zirconia/proprietary/vendor/lib64/libkeymaster_portable.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libkeymaster_portable.so \
    vendor/teracube/zirconia/proprietary/vendor/lib64/libkeystore-engine-wifi-hidl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libkeystore-engine-wifi-hidl.so \
    vendor/teracube/zirconia/proprietary/vendor/lib64/libkeystore-wifi-hidl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libkeystore-wifi-hidl.so \
    vendor/teracube/zirconia/proprietary/vendor/lib64/libkmsetkey.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libkmsetkey.so \
    vendor/teracube/zirconia/proprietary/vendor/lib64/libkphhelper.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libkphhelper.so \
    vendor/teracube/zirconia/proprietary/vendor/lib64/libkphproxy.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libkphproxy.so \
    vendor/teracube/zirconia/proprietary/vendor/lib64/libpl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libpl.so \
    vendor/teracube/zirconia/proprietary/vendor/lib64/libpuresoftkeymasterdevice.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libpuresoftkeymasterdevice.so \
    vendor/teracube/zirconia/proprietary/vendor/lib64/libsoft_attestation_cert.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsoft_attestation_cert.so \
    vendor/teracube/zirconia/proprietary/vendor/lib64/libsoftkeymasterdevice.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsoftkeymasterdevice.so \
    vendor/teracube/zirconia/proprietary/vendor/lib64/libteec.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libteec.so \
    vendor/teracube/zirconia/proprietary/vendor/lib64/libthha.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libthha.so \
    vendor/teracube/zirconia/proprietary/vendor/lib64/libtrusty.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libtrusty.so \
    vendor/teracube/zirconia/proprietary/vendor/lib64/libwapi.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libwapi.so \
    vendor/teracube/zirconia/proprietary/vendor/lib64/vendor.fpsensor.hardware.fpsensorhidlsvc@2.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/vendor.fpsensor.hardware.fpsensorhidlsvc@2.0.so \
    vendor/teracube/zirconia/proprietary/vendor/lib64/vendor.mediatek.hardware.keymaster_attestation@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/vendor.mediatek.hardware.keymaster_attestation@1.0.so \
    vendor/teracube/zirconia/proprietary/vendor/lib64/vendor.mediatek.hardware.keymaster_attestation@1.1.so:$(TARGET_COPY_OUT_VENDOR)/lib64/vendor.mediatek.hardware.keymaster_attestation@1.1.so \
    vendor/teracube/zirconia/proprietary/vendor/thh/ta/7778c03fc30c4dd0a319ea29643d4d4b.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/7778c03fc30c4dd0a319ea29643d4d4b.ta \
    vendor/teracube/zirconia/proprietary/vendor/thh/ta/TAs_list:$(TARGET_COPY_OUT_VENDOR)/thh/ta/TAs_list

PRODUCT_PACKAGES += \
    android.hardware.gatekeeper@1.0-service.itrusty
